apiVersion: v2
name: ingress-nginx
description: Umbrella chart to deploy cert-manager for certbot support
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx
