argo-cd:
  configs:
    cm:
      accounts.dev1: login
      accounts.dev1.enabled: "true"
      accounts.devops1: login
      accounts.devops1.enabled: "true"
    params:
      controller.sharding.algorithm: "round-robin"
    rbac:
      policy.csv: |
        p, role:sss-admin, *, *, *, allow
        p, role:team1, applications, get, team1/*, allow

        g, dev1, role:team1
        g, devops1, role:sss-admin

      policy.default: role:none

  controller:
    replicas: 2

  server:
    service:
      type: NodePort
    ingress:
      enabled: false
    extraArgs:
      - --insecure
