argo-cd:
  configs:
    cm:
      accounts.dev1: login
      accounts.dev1.enabled: "true"
      accounts.devops1: login
      accounts.devops1.enabled: "true"
    params:
      controller.sharding.algorithm: "round-robin"
    rbac:
      policy.csv: |
        p, role:admin, *, *, *, allow
        p, role:readonly, certificates, get, *, allow
        p, role:readonly, clusters, get, *, allow
        p, role:readonly, repositories, get, *, allow
        p, role:readonly, write-repositories, get, *, allow
        p, role:readonly, projects, get, *, allow
        p, role:readonly, applications, get, team1/*, allow

        g, dev1, role:readonly
        g, devops1, role:admin

      policy.default: role:readonly

  controller:
    replicas: 2

  server:
    service:
      type: NodePort
    ingress:
      enabled: false
    extraArgs:
      - --insecure
