# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: reloader-cluster2
#   namespace: argocd
#   labels:
#     team: dops
#     env: staging
# spec:
#   project: dops
#   destination:
#     server: https://192.168.1.84:61565
#     namespace: reloader
#   source:
#     repoURL: https://github.com/jmcc-sss/jmcc-test
#     targetRevision: main
#     path: argocd/dops-apps/reloader/base
#     helm:
#       # Otherwise it uses the name of the argocd application (reloader-cluster2) and names all the resource (reloader-cluster-xxx)
#       releaseName: reloader
#       valueFiles:
#         - values.yaml
#         - dev.yaml
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: false
#     syncOptions:
#       - CreateNamespace=true