# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: reloader-multisource
#   namespace: argocd
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - clustername: cluster1
#                   cluster: https://kubernetes.default.svc
#                   path: argocd/dops-apps/reloader/multisource
#                 # - clustername: cluster2
#                 #   cluster: https://192.168.1.84:61565
#                 #   path: argocd/dops-apps/reloader/cluster2
#           - list:
#               elements:
#                 - gitRepoURL: https://github.com/jmcc-sss/jmcc-test
#                   targetRevision: main
#                   valuesFile: $values/argocd/dops-apps/reloader/multisource/values.yaml
#                   helmRepoURL: https://stakater.github.io/stakater-charts
#                   helmChart: reloader
#                   helmChartVersion: 2.1.3
#                   namespace: reloader-multisource
#                   releaseName: reloader
#   template:
#     metadata:
#       name: "reloader-multisource-{{clustername}}"
#       annotations:
#         argocd.argoproj.io/manifest-generate-paths: .
#     spec:
#       project: dops
#       destination:
#         server: "{{cluster}}"
#         namespace: "{{namespace}}"
#       sources:
#         # Helm chart
#         - repoURL: "{{helmRepoURL}}"
#           chart: "{{helmChart}}"
#           targetRevision: "{{helmChartVersion}}"
#           helm:
#             # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
#             valueFiles:
#             - "{{valuesFile}}"
#         # Values from Git
#         - repoURL: "{{gitRepoURL}}"
#           targetRevision: "{{targetRevision}}"
#           ref: values
#         - repoURL: "{{gitRepoURL}}"
#           targetRevision: "{{targetRevision}}"
#           path: argocd/dops-apps/reloader/test
#       syncPolicy:
#         automated:
#           prune: false
#           selfHeal: false
#         syncOptions:
#           - CreateNamespace=true
#   # Prevents the applicationset from deleting resources if we remove the app
#   syncPolicy:
#     preserveResourcesOnDeletion: true
