apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certbot
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - clustername: cluster1
                  cluster: https://kubernetes.default.svc
                  path: argocd/dops-apps/certbot/
          - list:
              elements:
                - repoURL: https://github.com/jmcc-sss/jmcc-test
                  targetRevision: main
                  namespace: certbot
                  releaseName: certbot
  template:
    metadata:
      name: "certbot-{{clustername}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: dops
      destination:
        server: "{{cluster}}"
        namespace: "{{namespace}}"
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{targetRevision}}"
        path: "{{path}}"
        helm:
          releaseName: "{{releaseName}}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
  # Prevents the applicationset from deleting resources if we remove the app
  syncPolicy:
    preserveResourcesOnDeletion: true