apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certbot
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clustername: cluster1
            cluster: https://kubernetes.default.svc
            chartVersion: 1.17.2
            valuesFile: $values/argocd/dops-apps/certbot/cluster1/values.yaml
  template:
    metadata:
      name: "certbot-{{clustername}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: dops
      destination:
        server: "{{cluster}}"
        namespace: certbot
      sources:
        # Helm
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: "{{chartVersion}}"
          helm:
            releaseName: certbot
            valueFiles:
            - "{{valuesFile}}"
        # Git
        - repoURL: https://github.com/jmcc-sss/jmcc-test
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
  # Prevents the applicationset from deleting resources if we remove the app
  syncPolicy:
    preserveResourcesOnDeletion: true