apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clustername: cluster1
            cluster: https://kubernetes.default.svc
            chartVersion: 2.9.2
            valuesFile: $values/argocd/dops-apps/datadog-operator/cluster1/values.yaml
          - clustername: cluster2
            cluster: https://192.168.1.84:61565
            chartVersion: 2.9.2
            valuesFile: $values/argocd/dops-apps/datadog-operator/cluster2/values.yaml
  template:
    metadata:
      name: "datadog-operator-{{clustername}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: dops
      destination:
        server: "{{cluster}}"
        namespace: datadog
      sources:
        # Helm
        - repoURL: https://helm.datadoghq.com
          chart: datadog-operator
          targetRevision: "{{chartVersion}}"
          helm:
            releaseName: datadog-operator
            valueFiles:
            - "{{valuesFile}}"
        # Git
        - repoURL: https://github.com/jmcc-sss/jmcc-test
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
  # Prevents the applicationset from deleting resources if we remove the app
  syncPolicy:
    preserveResourcesOnDeletion: true