apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: cluster1
                  namespace: reloader
                  path: argocd/dops-apps/reloader/cluster1
                - cluster: cluster2
                  namespace: reloader
                  path: argocd/dops-apps/reloader/cluster2
          - list:
              elements:
                - repoURL: https://github.com/jmcc-sss/jmcc-test
                  targetRevision: main
                  valuesFile: values.yaml
  template:
    metadata:
      name: "{{cluster}}-reloader"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: reloader
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{targetRevision}}"
        path: "{{path}}"
        helm:
          releaseName: "reloader"
          valueFiles:
            - "{{valuesFile}}"
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true