apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clustername: cluster1
            cluster: https://kubernetes.default.svc
            chartVersion: 2.1.3
            valuesFile: $values/argocd/dops-apps/reloader/cluster1/values.yaml
        # - clustername: cluster2
        #   cluster: https://192.168.1.84:61565
        #   path: argocd/dops-apps/reloader/cluster2
  template:
    metadata:
      name: "reloader-{{clustername}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
    spec:
      project: dops
      destination:
        server: "{{cluster}}"
        namespace: reloader
      sources:
        # Helm
        - repoURL: https://stakater.github.io/stakater-charts
          chart: reloader
          targetRevision: "{{chartVersion}}"
          helm:
            releaseName: reloader
            valueFiles:
            - "{{valuesFile}}"
        # Git
        - repoURL: https://github.com/jmcc-sss/jmcc-test
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
  # Prevents the applicationset from deleting resources if we remove the app
  syncPolicy:
    preserveResourcesOnDeletion: true
