apiVersion: v2
name: ingress-nginx-internal
description: Umbrella chart to deploy ingress-nginx-internal
version: 0.1.0
dependencies:
  - name: ingress-nginx-internal
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx
