apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-dops
  namespace: argocd
spec:
  project: dops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/jmcc-sss/jmcc-test
    targetRevision: main
    path: argocd/argocd/dops-apps/
  syncPolicy: 
    automated:
      prune: false
      selfHeal: false
